vim.keymap.set("n", "j", "gj", { silent = true, nowait = true })
vim.keymap.set("n", "k", "gk", { silent = true, nowait = true })
vim.keymap.set("i", "jj", "<Esc>", { silent = true, nowait = true })
vim.keymap.set("i", "jk", "<Esc>", { silent = true, nowait = true })
vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "K", vim.lsp.buf.hover)
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename)
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action)
vim.keymap.set("n", "<leader>\\", "<cmd>ToggleTerm<cr>")
vim.keymap.set("t", "<leader>\\", [[<C-\><C-n><cmd>ToggleTerm<cr>]])
vim.keymap.set("n", "<leader>e", "<cmd>NvimTreeToggle<cr>")
--vim.keymap.set("n", "<leader>e", ":Lexplore<cr>", { silent = true })
vim.g.user_emmet_expandabbr_key = "<Tab>"
